### ISSUE TITLE
"Error deserializing object of type int" upon Executing "...ptgaze.exe --mode eye"

### ISSUE THREAD

**Issue by tslever** [hysts/pytorch_mpiigaze_demo#1]
To whom it may concern,

I installed ptgaze using "pip install ptgaze" on a Windows-10 PC running Python 3.8.5. Per your GitHub ReadMe, I ran "...ptgaze.exe --mode eye" in PowerShell as Administrator, where the ellipsis symbolized the rest of the absolute path to ptgaze.exe. The following error was output to console: "RuntimeError: Error deserializing object of type int". How do I get ptgaze working?

Best regards,

Tom Lever
<img width="950" alt="ptgaze_error" src="https://user-images.githubusercontent.com/46533664/91524822-30ed8180-e8ce-11ea-9ef0-24b98d5cdec0.PNG">

**Comment by hysts** [comment]
Hi, @tslever 

According to [this stackoverflow article](https://stackoverflow.com/questions/43981231/dlib-error-deserializing-object-of-type-short), the dlib's pretrained model doesn't seem to be downloaded and extracted properly. The code for downloading and extracting works on Mac and Linux, so I guess it's due to a difference of environment. I don't have a Windows environment, so I can't check it myself, but if you download the model from the URL in the article and put it in `~/.ptgaze/dlib/` (which I think is `C:/Users/your_user_name/.ptgaze/dlib` in case of Windows), i think it will work.

Hope it helps.

**Comment by tslever** [comment]
Thank you for your time and help. Your solution worked. While "C:\users\your_user_name\.ptgaze\dlib" already had a version of "shape_predictor_68_face_landmarks.dat", it seems that this model file somehow was not completed or corrupted during installation on my Windows-10 PC.

**Comment by hysts** [comment]
Glad to hear that. :)

**Comment by a-fly-fly-bird** [comment]
> Hi, @tslever
> 
> According to [this stackoverflow article](https://stackoverflow.com/questions/43981231/dlib-error-deserializing-object-of-type-short), the dlib's pretrained model doesn't seem to be downloaded and extracted properly. The code for downloading and extracting works on Mac and Linux, so I guess it's due to a difference of environment. I don't have a Windows environment, so I can't check it myself, but if you download the model from the URL in the article and put it in `~/.ptgaze/dlib/` (which I think is `C:/Users/your_user_name/.ptgaze/dlib` in case of Windows), i think it will work.
> 
> Hope it helps.

Thanks. It helps me a lot.
