### ISSUE TITLE
Video frame size 

### ISSUE THREAD

**Issue by DulminiD** [hysts/pytorch_mpiigaze_demo#5]
Hi, 
When using the system for a specified video file, the frame size is required to be around (650,500) otherwise the system fails. 
Is there a way to use the system without decreasing the frame size of the video. 

Thank you in advance.

**Comment by hysts** [comment]
Hi, @DulminiD 

What do you mean when you say the system fails? In my environment, the program works fine with videos of size 1920x1080 and 480x270. If you get an error, can you post the error message?

**Comment by DulminiD** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/53858570/115717773-1f467600-a398-11eb-9376-cbf946b07d56.png)
Hi, 
It does not throw an error it just stops running 

I added some logger.info and found out the issue is occurring at 

- File - face_landmark_estimator.py 
- Method - def _detect_faces_dlib(self, image: np.ndarray) -> List[Face]:
- Line - bboxes = self.detector(image[:, :, ::-1], 0) 

I'm running in a windows environment, could it be a reason for this? 

Thank you so much for the quick response.

**Comment by hysts** [comment]
@DulminiD 

> I'm running in a windows environment, could it be a reason for this?

That could be the cause. But I don't have a Windows environment, so I can't check it myself...

By the way, does the program crash with both smaller and larger video sizes? Also, the dlib face detector seems to be the cause, and what happens if you run the following code? Does it crash too?

```python
import cv2
import dlib

cap = cv2.VideoCapture('/path/to/your/video.mp4')
detector = dlib.get_frontal_face_detector()
ok, frame = cap.read()
boxes = detector(frame[:, :, ::-1], 0)
print(boxes)
```

And what happens if you use the S<sup>3</sup>FD face detector instead?
You can change face detector to S<sup>3</sup>FD by adding `--face-detector face_alignement_sfd`.

**Comment by DulminiD** [comment]
It works without any issues when face detector face_alignment_sfd. 
Yes, seems like the dlib face detector. 
Thank you so much
